# Altera platform Support
snd-soc-altera-i2s-objs = altera_i2s.o altera_i2s_idma.o

obj-$(CONFIG_SND_SOC_ALTERA_I2S) += snd-soc-altera-i2s.o

# Altera machine Support
snd-soc-altera-ch7033-objs := altera_ch7033.o

obj-$(CONFIG_SND_SOC_ALTERA_CH7033) += snd-soc-altera-ch7033.o

